### ISSUE TITLE
Refactor the /cart-review page

### ISSUE THREAD

**Issue by drew-chidi** [The0nis/Kulture#72]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/19674873/227805918-bb17419c-0806-4612-8dbb-e733fc8e3719.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/19674873/227805949-c7aa7789-e814-432c-a00c-303ab8ccaba4.png">

I feel a table would be best suited for the cart review list items. You can find attached the images of the prototype and the implemented design.

**Comment by Iamdonemmy** [comment]
Done.
